// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: coupon/v1/coupon.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取优惠券列表请求
type ListCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsRequest) Reset() {
	*x = ListCouponsRequest{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsRequest) ProtoMessage() {}

func (x *ListCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListCouponsRequest) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *ListCouponsRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ListCouponsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCouponsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取优惠券列表响应
type ListCouponsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*Coupon              `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsReply) Reset() {
	*x = ListCouponsReply{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReply) ProtoMessage() {}

func (x *ListCouponsReply) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReply.ProtoReflect.Descriptor instead.
func (*ListCouponsReply) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *ListCouponsReply) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListCouponsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取用户优惠券列表请求
type ListUserCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // available, used, expired
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsRequest) Reset() {
	*x = ListUserCouponsRequest{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsRequest) ProtoMessage() {}

func (x *ListUserCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListUserCouponsRequest) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserCouponsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUserCouponsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserCouponsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取用户优惠券列表响应
type ListUserCouponsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*UserCoupon          `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsReply) Reset() {
	*x = ListUserCouponsReply{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsReply) ProtoMessage() {}

func (x *ListUserCouponsReply) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsReply.ProtoReflect.Descriptor instead.
func (*ListUserCouponsReply) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserCouponsReply) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListUserCouponsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取优惠券详情请求
type GetCouponDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int32                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponDetailRequest) Reset() {
	*x = GetCouponDetailRequest{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponDetailRequest) ProtoMessage() {}

func (x *GetCouponDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponDetailRequest.ProtoReflect.Descriptor instead.
func (*GetCouponDetailRequest) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *GetCouponDetailRequest) GetCouponId() int32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

// 获取优惠券详情响应
type GetCouponDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *Coupon                `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	Rules         []*CouponRule          `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponDetailReply) Reset() {
	*x = GetCouponDetailReply{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponDetailReply) ProtoMessage() {}

func (x *GetCouponDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponDetailReply.ProtoReflect.Descriptor instead.
func (*GetCouponDetailReply) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *GetCouponDetailReply) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

func (x *GetCouponDetailReply) GetRules() []*CouponRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 领取优惠券请求
type ClaimCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int32                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponRequest) Reset() {
	*x = ClaimCouponRequest{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponRequest) ProtoMessage() {}

func (x *ClaimCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponRequest.ProtoReflect.Descriptor instead.
func (*ClaimCouponRequest) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimCouponRequest) GetCouponId() int32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *ClaimCouponRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 领取优惠券响应
type ClaimCouponReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserCouponId  int64                  `protobuf:"varint,3,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponReply) Reset() {
	*x = ClaimCouponReply{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponReply) ProtoMessage() {}

func (x *ClaimCouponReply) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponReply.ProtoReflect.Descriptor instead.
func (*ClaimCouponReply) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimCouponReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimCouponReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClaimCouponReply) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

// 计算可用优惠券请求
type CalculateAvailableCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	StoreId       int32                  `protobuf:"varint,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateAvailableCouponsRequest) Reset() {
	*x = CalculateAvailableCouponsRequest{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateAvailableCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAvailableCouponsRequest) ProtoMessage() {}

func (x *CalculateAvailableCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAvailableCouponsRequest.ProtoReflect.Descriptor instead.
func (*CalculateAvailableCouponsRequest) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateAvailableCouponsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalculateAvailableCouponsRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CalculateAvailableCouponsRequest) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CalculateAvailableCouponsRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

// 计算可用优惠券响应
type CalculateAvailableCouponsReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AvailableCoupons   []*AvailableCoupon     `protobuf:"bytes,1,rep,name=available_coupons,json=availableCoupons,proto3" json:"available_coupons,omitempty"`
	BestDiscountAmount string                 `protobuf:"bytes,2,opt,name=best_discount_amount,json=bestDiscountAmount,proto3" json:"best_discount_amount,omitempty"`
	BestCouponId       int64                  `protobuf:"varint,3,opt,name=best_coupon_id,json=bestCouponId,proto3" json:"best_coupon_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CalculateAvailableCouponsReply) Reset() {
	*x = CalculateAvailableCouponsReply{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateAvailableCouponsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAvailableCouponsReply) ProtoMessage() {}

func (x *CalculateAvailableCouponsReply) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAvailableCouponsReply.ProtoReflect.Descriptor instead.
func (*CalculateAvailableCouponsReply) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{9}
}

func (x *CalculateAvailableCouponsReply) GetAvailableCoupons() []*AvailableCoupon {
	if x != nil {
		return x.AvailableCoupons
	}
	return nil
}

func (x *CalculateAvailableCouponsReply) GetBestDiscountAmount() string {
	if x != nil {
		return x.BestDiscountAmount
	}
	return ""
}

func (x *CalculateAvailableCouponsReply) GetBestCouponId() int64 {
	if x != nil {
		return x.BestCouponId
	}
	return 0
}

// 优惠券信息
type Coupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscountName   string                 `protobuf:"bytes,2,opt,name=discount_name,json=discountName,proto3" json:"discount_name,omitempty"`
	Classify       string                 `protobuf:"bytes,3,opt,name=classify,proto3" json:"classify,omitempty"`
	StoreId        int32                  `protobuf:"varint,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	DiscountAmount string                 `protobuf:"bytes,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	MinOrderAmount string                 `protobuf:"bytes,6,opt,name=min_order_amount,json=minOrderAmount,proto3" json:"min_order_amount,omitempty"`
	StartTime      string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxIssue       int32                  `protobuf:"varint,9,opt,name=max_issue,json=maxIssue,proto3" json:"max_issue,omitempty"`
	MaxPerUser     int32                  `protobuf:"varint,10,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	IssuedCount    int32                  `protobuf:"varint,11,opt,name=issued_count,json=issuedCount,proto3" json:"issued_count,omitempty"`
	UsedCount      int32                  `protobuf:"varint,12,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{10}
}

func (x *Coupon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Coupon) GetDiscountName() string {
	if x != nil {
		return x.DiscountName
	}
	return ""
}

func (x *Coupon) GetClassify() string {
	if x != nil {
		return x.Classify
	}
	return ""
}

func (x *Coupon) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *Coupon) GetDiscountAmount() string {
	if x != nil {
		return x.DiscountAmount
	}
	return ""
}

func (x *Coupon) GetMinOrderAmount() string {
	if x != nil {
		return x.MinOrderAmount
	}
	return ""
}

func (x *Coupon) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Coupon) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Coupon) GetMaxIssue() int32 {
	if x != nil {
		return x.MaxIssue
	}
	return 0
}

func (x *Coupon) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *Coupon) GetIssuedCount() int32 {
	if x != nil {
		return x.IssuedCount
	}
	return 0
}

func (x *Coupon) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

// 用户优惠券
type UserCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponId      int32                  `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ClaimTime     string                 `protobuf:"bytes,5,opt,name=claim_time,json=claimTime,proto3" json:"claim_time,omitempty"`
	UseTime       string                 `protobuf:"bytes,6,opt,name=use_time,json=useTime,proto3" json:"use_time,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Coupon        *Coupon                `protobuf:"bytes,8,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{11}
}

func (x *UserCoupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetCouponId() int32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UserCoupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserCoupon) GetClaimTime() string {
	if x != nil {
		return x.ClaimTime
	}
	return ""
}

func (x *UserCoupon) GetUseTime() string {
	if x != nil {
		return x.UseTime
	}
	return ""
}

func (x *UserCoupon) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *UserCoupon) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// 优惠券规则
type CouponRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscountId    int32                  `protobuf:"varint,2,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"`
	RuleKey       int32                  `protobuf:"varint,3,opt,name=rule_key,json=ruleKey,proto3" json:"rule_key,omitempty"`
	RuleValue     string                 `protobuf:"bytes,4,opt,name=rule_value,json=ruleValue,proto3" json:"rule_value,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	DrugId        int32                  `protobuf:"varint,6,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	Astrict       string                 `protobuf:"bytes,7,opt,name=astrict,proto3" json:"astrict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponRule) Reset() {
	*x = CouponRule{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponRule) ProtoMessage() {}

func (x *CouponRule) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponRule.ProtoReflect.Descriptor instead.
func (*CouponRule) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{12}
}

func (x *CouponRule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponRule) GetDiscountId() int32 {
	if x != nil {
		return x.DiscountId
	}
	return 0
}

func (x *CouponRule) GetRuleKey() int32 {
	if x != nil {
		return x.RuleKey
	}
	return 0
}

func (x *CouponRule) GetRuleValue() string {
	if x != nil {
		return x.RuleValue
	}
	return ""
}

func (x *CouponRule) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CouponRule) GetDrugId() int32 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *CouponRule) GetAstrict() string {
	if x != nil {
		return x.Astrict
	}
	return ""
}

// 订单项
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        int64                  `protobuf:"varint,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{13}
}

func (x *OrderItem) GetDrugId() int64 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

// 可用优惠券
type AvailableCoupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId   int64                  `protobuf:"varint,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	Coupon         *Coupon                `protobuf:"bytes,2,opt,name=coupon,proto3" json:"coupon,omitempty"`
	DiscountAmount string                 `protobuf:"bytes,3,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount    string                 `protobuf:"bytes,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	CanUse         bool                   `protobuf:"varint,5,opt,name=can_use,json=canUse,proto3" json:"can_use,omitempty"`
	Reason         string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvailableCoupon) Reset() {
	*x = AvailableCoupon{}
	mi := &file_coupon_v1_coupon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCoupon) ProtoMessage() {}

func (x *AvailableCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_v1_coupon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCoupon.ProtoReflect.Descriptor instead.
func (*AvailableCoupon) Descriptor() ([]byte, []int) {
	return file_coupon_v1_coupon_proto_rawDescGZIP(), []int{14}
}

func (x *AvailableCoupon) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *AvailableCoupon) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

func (x *AvailableCoupon) GetDiscountAmount() string {
	if x != nil {
		return x.DiscountAmount
	}
	return ""
}

func (x *AvailableCoupon) GetFinalAmount() string {
	if x != nil {
		return x.FinalAmount
	}
	return ""
}

func (x *AvailableCoupon) GetCanUse() bool {
	if x != nil {
		return x.CanUse
	}
	return false
}

func (x *AvailableCoupon) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_coupon_v1_coupon_proto protoreflect.FileDescriptor

const file_coupon_v1_coupon_proto_rawDesc = "" +
	"\n" +
	"\x16coupon/v1/coupon.proto\x12\rapi.coupon.v1\x1a\x1cgoogle/api/annotations.proto\"`\n" +
	"\x12ListCouponsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Y\n" +
	"\x10ListCouponsReply\x12/\n" +
	"\acoupons\x18\x01 \x03(\v2\x15.api.coupon.v1.CouponR\acoupons\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"z\n" +
	"\x16ListUserCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"a\n" +
	"\x14ListUserCouponsReply\x123\n" +
	"\acoupons\x18\x01 \x03(\v2\x19.api.coupon.v1.UserCouponR\acoupons\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"5\n" +
	"\x16GetCouponDetailRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x05R\bcouponId\"v\n" +
	"\x14GetCouponDetailReply\x12-\n" +
	"\x06coupon\x18\x01 \x01(\v2\x15.api.coupon.v1.CouponR\x06coupon\x12/\n" +
	"\x05rules\x18\x02 \x03(\v2\x19.api.coupon.v1.CouponRuleR\x05rules\"J\n" +
	"\x12ClaimCouponRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x05R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"l\n" +
	"\x10ClaimCouponReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0euser_coupon_id\x18\x03 \x01(\x03R\fuserCouponId\"\xa9\x01\n" +
	" CalculateAvailableCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.api.coupon.v1.OrderItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\x12\x19\n" +
	"\bstore_id\x18\x04 \x01(\x05R\astoreId\"\xc5\x01\n" +
	"\x1eCalculateAvailableCouponsReply\x12K\n" +
	"\x11available_coupons\x18\x01 \x03(\v2\x1e.api.coupon.v1.AvailableCouponR\x10availableCoupons\x120\n" +
	"\x14best_discount_amount\x18\x02 \x01(\tR\x12bestDiscountAmount\x12$\n" +
	"\x0ebest_coupon_id\x18\x03 \x01(\x03R\fbestCouponId\"\x82\x03\n" +
	"\x06Coupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rdiscount_name\x18\x02 \x01(\tR\fdiscountName\x12\x1a\n" +
	"\bclassify\x18\x03 \x01(\tR\bclassify\x12\x19\n" +
	"\bstore_id\x18\x04 \x01(\x05R\astoreId\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\tR\x0ediscountAmount\x12(\n" +
	"\x10min_order_amount\x18\x06 \x01(\tR\x0eminOrderAmount\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\x12\x1b\n" +
	"\tmax_issue\x18\t \x01(\x05R\bmaxIssue\x12 \n" +
	"\fmax_per_user\x18\n" +
	" \x01(\x05R\n" +
	"maxPerUser\x12!\n" +
	"\fissued_count\x18\v \x01(\x05R\vissuedCount\x12\x1d\n" +
	"\n" +
	"used_count\x18\f \x01(\x05R\tusedCount\"\xf4\x01\n" +
	"\n" +
	"UserCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\x05R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"claim_time\x18\x05 \x01(\tR\tclaimTime\x12\x19\n" +
	"\buse_time\x18\x06 \x01(\tR\auseTime\x12\x1f\n" +
	"\vexpire_time\x18\a \x01(\tR\n" +
	"expireTime\x12-\n" +
	"\x06coupon\x18\b \x01(\v2\x15.api.coupon.v1.CouponR\x06coupon\"\xc6\x01\n" +
	"\n" +
	"CouponRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdiscount_id\x18\x02 \x01(\x05R\n" +
	"discountId\x12\x19\n" +
	"\brule_key\x18\x03 \x01(\x05R\aruleKey\x12\x1d\n" +
	"\n" +
	"rule_value\x18\x04 \x01(\tR\truleValue\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x17\n" +
	"\adrug_id\x18\x06 \x01(\x05R\x06drugId\x12\x18\n" +
	"\aastrict\x18\a \x01(\tR\aastrict\"V\n" +
	"\tOrderItem\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\x03R\x06drugId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\"\xe3\x01\n" +
	"\x0fAvailableCoupon\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\x03R\fuserCouponId\x12-\n" +
	"\x06coupon\x18\x02 \x01(\v2\x15.api.coupon.v1.CouponR\x06coupon\x12'\n" +
	"\x0fdiscount_amount\x18\x03 \x01(\tR\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\tR\vfinalAmount\x12\x17\n" +
	"\acan_use\x18\x05 \x01(\bR\x06canUse\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason2\xae\x05\n" +
	"\rCouponService\x12j\n" +
	"\vListCoupons\x12!.api.coupon.v1.ListCouponsRequest\x1a\x1f.api.coupon.v1.ListCouponsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/coupons\x12\x86\x01\n" +
	"\x0fListUserCoupons\x12%.api.coupon.v1.ListUserCouponsRequest\x1a#.api.coupon.v1.ListUserCouponsReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/users/{user_id}/coupons\x12\x82\x01\n" +
	"\x0fGetCouponDetail\x12%.api.coupon.v1.GetCouponDetailRequest\x1a#.api.coupon.v1.GetCouponDetailReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/coupons/{coupon_id}\x12\x7f\n" +
	"\vClaimCoupon\x12!.api.coupon.v1.ClaimCouponRequest\x1a\x1f.api.coupon.v1.ClaimCouponReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/coupons/{coupon_id}/claim\x12\xa1\x01\n" +
	"\x19CalculateAvailableCoupons\x12/.api.coupon.v1.CalculateAvailableCouponsRequest\x1a-.api.coupon.v1.CalculateAvailableCouponsReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/coupons/calculateB Z\x1ekratos_client/api/coupon/v1;v1b\x06proto3"

var (
	file_coupon_v1_coupon_proto_rawDescOnce sync.Once
	file_coupon_v1_coupon_proto_rawDescData []byte
)

func file_coupon_v1_coupon_proto_rawDescGZIP() []byte {
	file_coupon_v1_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_v1_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_v1_coupon_proto_rawDesc), len(file_coupon_v1_coupon_proto_rawDesc)))
	})
	return file_coupon_v1_coupon_proto_rawDescData
}

var file_coupon_v1_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_coupon_v1_coupon_proto_goTypes = []any{
	(*ListCouponsRequest)(nil),               // 0: api.coupon.v1.ListCouponsRequest
	(*ListCouponsReply)(nil),                 // 1: api.coupon.v1.ListCouponsReply
	(*ListUserCouponsRequest)(nil),           // 2: api.coupon.v1.ListUserCouponsRequest
	(*ListUserCouponsReply)(nil),             // 3: api.coupon.v1.ListUserCouponsReply
	(*GetCouponDetailRequest)(nil),           // 4: api.coupon.v1.GetCouponDetailRequest
	(*GetCouponDetailReply)(nil),             // 5: api.coupon.v1.GetCouponDetailReply
	(*ClaimCouponRequest)(nil),               // 6: api.coupon.v1.ClaimCouponRequest
	(*ClaimCouponReply)(nil),                 // 7: api.coupon.v1.ClaimCouponReply
	(*CalculateAvailableCouponsRequest)(nil), // 8: api.coupon.v1.CalculateAvailableCouponsRequest
	(*CalculateAvailableCouponsReply)(nil),   // 9: api.coupon.v1.CalculateAvailableCouponsReply
	(*Coupon)(nil),                           // 10: api.coupon.v1.Coupon
	(*UserCoupon)(nil),                       // 11: api.coupon.v1.UserCoupon
	(*CouponRule)(nil),                       // 12: api.coupon.v1.CouponRule
	(*OrderItem)(nil),                        // 13: api.coupon.v1.OrderItem
	(*AvailableCoupon)(nil),                  // 14: api.coupon.v1.AvailableCoupon
}
var file_coupon_v1_coupon_proto_depIdxs = []int32{
	10, // 0: api.coupon.v1.ListCouponsReply.coupons:type_name -> api.coupon.v1.Coupon
	11, // 1: api.coupon.v1.ListUserCouponsReply.coupons:type_name -> api.coupon.v1.UserCoupon
	10, // 2: api.coupon.v1.GetCouponDetailReply.coupon:type_name -> api.coupon.v1.Coupon
	12, // 3: api.coupon.v1.GetCouponDetailReply.rules:type_name -> api.coupon.v1.CouponRule
	13, // 4: api.coupon.v1.CalculateAvailableCouponsRequest.items:type_name -> api.coupon.v1.OrderItem
	14, // 5: api.coupon.v1.CalculateAvailableCouponsReply.available_coupons:type_name -> api.coupon.v1.AvailableCoupon
	10, // 6: api.coupon.v1.UserCoupon.coupon:type_name -> api.coupon.v1.Coupon
	10, // 7: api.coupon.v1.AvailableCoupon.coupon:type_name -> api.coupon.v1.Coupon
	0,  // 8: api.coupon.v1.CouponService.ListCoupons:input_type -> api.coupon.v1.ListCouponsRequest
	2,  // 9: api.coupon.v1.CouponService.ListUserCoupons:input_type -> api.coupon.v1.ListUserCouponsRequest
	4,  // 10: api.coupon.v1.CouponService.GetCouponDetail:input_type -> api.coupon.v1.GetCouponDetailRequest
	6,  // 11: api.coupon.v1.CouponService.ClaimCoupon:input_type -> api.coupon.v1.ClaimCouponRequest
	8,  // 12: api.coupon.v1.CouponService.CalculateAvailableCoupons:input_type -> api.coupon.v1.CalculateAvailableCouponsRequest
	1,  // 13: api.coupon.v1.CouponService.ListCoupons:output_type -> api.coupon.v1.ListCouponsReply
	3,  // 14: api.coupon.v1.CouponService.ListUserCoupons:output_type -> api.coupon.v1.ListUserCouponsReply
	5,  // 15: api.coupon.v1.CouponService.GetCouponDetail:output_type -> api.coupon.v1.GetCouponDetailReply
	7,  // 16: api.coupon.v1.CouponService.ClaimCoupon:output_type -> api.coupon.v1.ClaimCouponReply
	9,  // 17: api.coupon.v1.CouponService.CalculateAvailableCoupons:output_type -> api.coupon.v1.CalculateAvailableCouponsReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_coupon_v1_coupon_proto_init() }
func file_coupon_v1_coupon_proto_init() {
	if File_coupon_v1_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_v1_coupon_proto_rawDesc), len(file_coupon_v1_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_v1_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_v1_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_v1_coupon_proto_msgTypes,
	}.Build()
	File_coupon_v1_coupon_proto = out.File
	file_coupon_v1_coupon_proto_goTypes = nil
	file_coupon_v1_coupon_proto_depIdxs = nil
}
