/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    FeedbackButton: typeof import('./src/components/FeedbackButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastMessage: typeof import('./src/components/ToastMessage.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanTag: typeof import('vant/es')['Tag']
  }
}
