-- 检查mt_doctors表的完整结构
DESCRIBE mt_doctors;

-- 查看所有字段及其约束
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_TYPE,
    COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'mt_doctors' 
AND TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION;

-- 检查是否有password_hash字段
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'mt_doctors' 
AND COLUMN_NAME LIKE '%password%'
AND TABLE_SCHEMA = DATABASE();

-- 检查是否有其他必填字段
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'mt_doctors' 
AND IS_NULLABLE = 'NO'
AND COLUMN_NAME NOT IN ('id', 'created_at', 'updated_at', 'deleted_at')
AND TABLE_SCHEMA = DATABASE(); 