// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: payment/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建支付请求
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                // 用户token
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                            // 商品标题
	TotalAmount   string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 支付金额
	OrderType     string                 `protobuf:"bytes,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`       // 订单类型 (drug_order, consultation_order)
	BusinessId    string                 `protobuf:"bytes,5,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`    // 业务ID (药品订单ID或咨询订单ID)
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                    // 订单描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreatePaymentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePaymentRequest) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CreatePaymentRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *CreatePaymentRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 创建支付响应
type CreatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,3,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // 支付链接
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePaymentReply) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreatePaymentReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 支付通知请求
type PaymentNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 支付宝回调参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotifyRequest) Reset() {
	*x = PaymentNotifyRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotifyRequest) ProtoMessage() {}

func (x *PaymentNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotifyRequest.ProtoReflect.Descriptor instead.
func (*PaymentNotifyRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentNotifyRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 支付通知响应
type PaymentNotifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // success 或 fail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotifyReply) Reset() {
	*x = PaymentNotifyReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotifyReply) ProtoMessage() {}

func (x *PaymentNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotifyReply.ProtoReflect.Descriptor instead.
func (*PaymentNotifyReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentNotifyReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// 查询支付请求
type QueryPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                    // 用户token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRequest) Reset() {
	*x = QueryPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRequest) ProtoMessage() {}

func (x *QueryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *QueryPaymentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 查询支付响应
type QueryPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PaymentInfo   *PaymentInfo           `protobuf:"bytes,3,opt,name=payment_info,json=paymentInfo,proto3" json:"payment_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentReply) Reset() {
	*x = QueryPaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReply) ProtoMessage() {}

func (x *QueryPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReply.ProtoReflect.Descriptor instead.
func (*QueryPaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *QueryPaymentReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryPaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryPaymentReply) GetPaymentInfo() *PaymentInfo {
	if x != nil {
		return x.PaymentInfo
	}
	return nil
}

// 支付返回请求
type PaymentReturnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 支付宝返回参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReturnRequest) Reset() {
	*x = PaymentReturnRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReturnRequest) ProtoMessage() {}

func (x *PaymentReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReturnRequest.ProtoReflect.Descriptor instead.
func (*PaymentReturnRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentReturnRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 支付返回响应
type PaymentReturnReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"` // 重定向地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReturnReply) Reset() {
	*x = PaymentReturnReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReturnReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReturnReply) ProtoMessage() {}

func (x *PaymentReturnReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReturnReply.ProtoReflect.Descriptor instead.
func (*PaymentReturnReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentReturnReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentReturnReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentReturnReply) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

// 支付信息
type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`             // 订单号
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`             // 支付宝交易号
	TotalAmount   string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 支付金额
	TradeStatus   string                 `protobuf:"bytes,4,opt,name=trade_status,json=tradeStatus,proto3" json:"trade_status,omitempty"` // 交易状态
	PayTime       string                 `protobuf:"bytes,5,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`             // 支付时间
	Subject       string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`                            // 商品标题
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentInfo) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentInfo) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *PaymentInfo) GetTradeStatus() string {
	if x != nil {
		return x.TradeStatus
	}
	return ""
}

func (x *PaymentInfo) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *PaymentInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\x0eapi.payment.v1\x1a\x1cgoogle/api/annotations.proto\"\xcb\x01\n" +
	"\x14CreatePaymentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\x12\x1d\n" +
	"\n" +
	"order_type\x18\x04 \x01(\tR\torderType\x12\x1f\n" +
	"\vbusiness_id\x18\x05 \x01(\tR\n" +
	"businessId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"~\n" +
	"\x12CreatePaymentReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vpayment_url\x18\x03 \x01(\tR\n" +
	"paymentUrl\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\"\x9b\x01\n" +
	"\x14PaymentNotifyRequest\x12H\n" +
	"\x06params\x18\x01 \x03(\v20.api.payment.v1.PaymentNotifyRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12PaymentNotifyReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"F\n" +
	"\x13QueryPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x81\x01\n" +
	"\x11QueryPaymentReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\fpayment_info\x18\x03 \x01(\v2\x1b.api.payment.v1.PaymentInfoR\vpaymentInfo\"\x9b\x01\n" +
	"\x14PaymentReturnRequest\x12H\n" +
	"\x06params\x18\x01 \x03(\v20.api.payment.v1.PaymentReturnRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x12PaymentReturnReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl\"\xbe\x01\n" +
	"\vPaymentInfo\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\x12!\n" +
	"\ftrade_status\x18\x04 \x01(\tR\vtradeStatus\x12\x19\n" +
	"\bpay_time\x18\x05 \x01(\tR\apayTime\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject2\xe7\x03\n" +
	"\aPayment\x12x\n" +
	"\rCreatePayment\x12$.api.payment.v1.CreatePaymentRequest\x1a\".api.payment.v1.CreatePaymentReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/payment/create\x12x\n" +
	"\rPaymentNotify\x12$.api.payment.v1.PaymentNotifyRequest\x1a\".api.payment.v1.PaymentNotifyReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/payment/notify\x12q\n" +
	"\fQueryPayment\x12#.api.payment.v1.QueryPaymentRequest\x1a!.api.payment.v1.QueryPaymentReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/payment/query\x12u\n" +
	"\rPaymentReturn\x12$.api.payment.v1.PaymentReturnRequest\x1a\".api.payment.v1.PaymentReturnReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/payment/returnB!Z\x1fkratos_client/api/payment/v1;v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_payment_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil), // 0: api.payment.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),   // 1: api.payment.v1.CreatePaymentReply
	(*PaymentNotifyRequest)(nil), // 2: api.payment.v1.PaymentNotifyRequest
	(*PaymentNotifyReply)(nil),   // 3: api.payment.v1.PaymentNotifyReply
	(*QueryPaymentRequest)(nil),  // 4: api.payment.v1.QueryPaymentRequest
	(*QueryPaymentReply)(nil),    // 5: api.payment.v1.QueryPaymentReply
	(*PaymentReturnRequest)(nil), // 6: api.payment.v1.PaymentReturnRequest
	(*PaymentReturnReply)(nil),   // 7: api.payment.v1.PaymentReturnReply
	(*PaymentInfo)(nil),          // 8: api.payment.v1.PaymentInfo
	nil,                          // 9: api.payment.v1.PaymentNotifyRequest.ParamsEntry
	nil,                          // 10: api.payment.v1.PaymentReturnRequest.ParamsEntry
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	9,  // 0: api.payment.v1.PaymentNotifyRequest.params:type_name -> api.payment.v1.PaymentNotifyRequest.ParamsEntry
	8,  // 1: api.payment.v1.QueryPaymentReply.payment_info:type_name -> api.payment.v1.PaymentInfo
	10, // 2: api.payment.v1.PaymentReturnRequest.params:type_name -> api.payment.v1.PaymentReturnRequest.ParamsEntry
	0,  // 3: api.payment.v1.Payment.CreatePayment:input_type -> api.payment.v1.CreatePaymentRequest
	2,  // 4: api.payment.v1.Payment.PaymentNotify:input_type -> api.payment.v1.PaymentNotifyRequest
	4,  // 5: api.payment.v1.Payment.QueryPayment:input_type -> api.payment.v1.QueryPaymentRequest
	6,  // 6: api.payment.v1.Payment.PaymentReturn:input_type -> api.payment.v1.PaymentReturnRequest
	1,  // 7: api.payment.v1.Payment.CreatePayment:output_type -> api.payment.v1.CreatePaymentReply
	3,  // 8: api.payment.v1.Payment.PaymentNotify:output_type -> api.payment.v1.PaymentNotifyReply
	5,  // 9: api.payment.v1.Payment.QueryPayment:output_type -> api.payment.v1.QueryPaymentReply
	7,  // 10: api.payment.v1.Payment.PaymentReturn:output_type -> api.payment.v1.PaymentReturnReply
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
