server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:1c96b09a0f66835d5c372d1e4064e07e@tcp(14.103.134.228:3306)/Health_Medicine_E_Station?parseTime=True&loc=Local
  redis:
    addr: 14.103.134.228:6379
    password: 1c96b09a0f66835d5c372d1e4064e07e
    read_timeout: 0.2s
    write_timeout: 0.2s
  # elasticsearch:
  #   addresses:
  #     - http://localhost:9200
  #   username: ""
  #   password: ""
  #   timeout: 5s
  #   max_retries: 3
