server:
  http:
    addr: 0.0.0.0:8888
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: sqlite
    source: "dev.db"
  # Redis配置 - 注释掉以禁用Redis
  # redis:
  #   addr: localhost:6379
  #   password: ""
  #   read_timeout: 0.2s
  #   write_timeout: 0.2s
