// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: drug/v1/drug.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDrugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrugRequest) Reset() {
	*x = GetDrugRequest{}
	mi := &file_drug_v1_drug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrugRequest) ProtoMessage() {}

func (x *GetDrugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrugRequest.ProtoReflect.Descriptor instead.
func (*GetDrugRequest) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{0}
}

func (x *GetDrugRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDrugReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Drug          *InfoDrug              `protobuf:"bytes,3,opt,name=drug,proto3" json:"drug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDrugReply) Reset() {
	*x = GetDrugReply{}
	mi := &file_drug_v1_drug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDrugReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrugReply) ProtoMessage() {}

func (x *GetDrugReply) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrugReply.ProtoReflect.Descriptor instead.
func (*GetDrugReply) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{1}
}

func (x *GetDrugReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDrugReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetDrugReply) GetDrug() *InfoDrug {
	if x != nil {
		return x.Drug
	}
	return nil
}

type InfoDrug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugName      string                 `protobuf:"bytes,1,opt,name=drug_name,json=drugName,proto3" json:"drug_name,omitempty"`
	Specification string                 `protobuf:"bytes,2,opt,name=specification,proto3" json:"specification,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	SalesVolume   float64                `protobuf:"fixed64,4,opt,name=sales_volume,json=salesVolume,proto3" json:"sales_volume,omitempty"`
	Inventory     int64                  `protobuf:"varint,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	ExhibitionUrl string                 `protobuf:"bytes,6,opt,name=exhibition_url,json=exhibitionUrl,proto3" json:"exhibition_url,omitempty"`
	Guide         *GuideInfo             `protobuf:"bytes,7,opt,name=guide,proto3" json:"guide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoDrug) Reset() {
	*x = InfoDrug{}
	mi := &file_drug_v1_drug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoDrug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoDrug) ProtoMessage() {}

func (x *InfoDrug) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoDrug.ProtoReflect.Descriptor instead.
func (*InfoDrug) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{2}
}

func (x *InfoDrug) GetDrugName() string {
	if x != nil {
		return x.DrugName
	}
	return ""
}

func (x *InfoDrug) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *InfoDrug) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InfoDrug) GetSalesVolume() float64 {
	if x != nil {
		return x.SalesVolume
	}
	return 0
}

func (x *InfoDrug) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *InfoDrug) GetExhibitionUrl() string {
	if x != nil {
		return x.ExhibitionUrl
	}
	return ""
}

func (x *InfoDrug) GetGuide() *GuideInfo {
	if x != nil {
		return x.Guide
	}
	return nil
}

type GuideInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MajorFunction  string                 `protobuf:"bytes,1,opt,name=major_function,json=majorFunction,proto3" json:"major_function,omitempty"`
	UsageAndDosage string                 `protobuf:"bytes,2,opt,name=usage_and_dosage,json=usageAndDosage,proto3" json:"usage_and_dosage,omitempty"`
	Taboos         string                 `protobuf:"bytes,3,opt,name=taboos,proto3" json:"taboos,omitempty"`
	SpecialCrowd   string                 `protobuf:"bytes,4,opt,name=special_crowd,json=specialCrowd,proto3" json:"special_crowd,omitempty"`
	Condition      string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GuideInfo) Reset() {
	*x = GuideInfo{}
	mi := &file_drug_v1_drug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuideInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideInfo) ProtoMessage() {}

func (x *GuideInfo) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideInfo.ProtoReflect.Descriptor instead.
func (*GuideInfo) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{3}
}

func (x *GuideInfo) GetMajorFunction() string {
	if x != nil {
		return x.MajorFunction
	}
	return ""
}

func (x *GuideInfo) GetUsageAndDosage() string {
	if x != nil {
		return x.UsageAndDosage
	}
	return ""
}

func (x *GuideInfo) GetTaboos() string {
	if x != nil {
		return x.Taboos
	}
	return ""
}

func (x *GuideInfo) GetSpecialCrowd() string {
	if x != nil {
		return x.SpecialCrowd
	}
	return ""
}

func (x *GuideInfo) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type GetExplainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplainRequest) Reset() {
	*x = GetExplainRequest{}
	mi := &file_drug_v1_drug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplainRequest) ProtoMessage() {}

func (x *GetExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplainRequest.ProtoReflect.Descriptor instead.
func (*GetExplainRequest) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{4}
}

func (x *GetExplainRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExplainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Explain       *ExplainInfo           `protobuf:"bytes,3,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplainReply) Reset() {
	*x = GetExplainReply{}
	mi := &file_drug_v1_drug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplainReply) ProtoMessage() {}

func (x *GetExplainReply) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplainReply.ProtoReflect.Descriptor instead.
func (*GetExplainReply) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{5}
}

func (x *GetExplainReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetExplainReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetExplainReply) GetExplain() *ExplainInfo {
	if x != nil {
		return x.Explain
	}
	return nil
}

type ExplainInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CommonName             string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	GoodsName              string                 `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	Component              string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Taboos                 string                 `protobuf:"bytes,4,opt,name=taboos,proto3" json:"taboos,omitempty"`
	Function               string                 `protobuf:"bytes,5,opt,name=function,proto3" json:"function,omitempty"`
	UsageAndDosage         string                 `protobuf:"bytes,7,opt,name=usage_and_dosage,json=usageAndDosage,proto3" json:"usage_and_dosage,omitempty"`
	Character              string                 `protobuf:"bytes,8,opt,name=character,proto3" json:"character,omitempty"`
	PackagingSpecification string                 `protobuf:"bytes,9,opt,name=packaging_specification,json=packagingSpecification,proto3" json:"packaging_specification,omitempty"`
	BadnessReaction        string                 `protobuf:"bytes,10,opt,name=badness_reaction,json=badnessReaction,proto3" json:"badness_reaction,omitempty"`
	Condition              string                 `protobuf:"bytes,11,opt,name=condition,proto3" json:"condition,omitempty"`
	ValidTime              string                 `protobuf:"bytes,12,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	Notice                 string                 `protobuf:"bytes,13,opt,name=notice,proto3" json:"notice,omitempty"`
	Interaction            string                 `protobuf:"bytes,14,opt,name=interaction,proto3" json:"interaction,omitempty"`
	RatifyNumber           string                 `protobuf:"bytes,15,opt,name=ratify_number,json=ratifyNumber,proto3" json:"ratify_number,omitempty"`
	Manufacturer           string                 `protobuf:"bytes,16,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	StandardNumber         string                 `protobuf:"bytes,17,opt,name=standard_number,json=standardNumber,proto3" json:"standard_number,omitempty"`
	Possessor              string                 `protobuf:"bytes,18,opt,name=possessor,proto3" json:"possessor,omitempty"`
	Address                string                 `protobuf:"bytes,19,opt,name=address,proto3" json:"address,omitempty"`
	Specification          string                 `protobuf:"bytes,20,opt,name=specification,proto3" json:"specification,omitempty"`
	DosageForm             string                 `protobuf:"bytes,21,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExplainInfo) Reset() {
	*x = ExplainInfo{}
	mi := &file_drug_v1_drug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainInfo) ProtoMessage() {}

func (x *ExplainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainInfo.ProtoReflect.Descriptor instead.
func (*ExplainInfo) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{6}
}

func (x *ExplainInfo) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *ExplainInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ExplainInfo) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ExplainInfo) GetTaboos() string {
	if x != nil {
		return x.Taboos
	}
	return ""
}

func (x *ExplainInfo) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ExplainInfo) GetUsageAndDosage() string {
	if x != nil {
		return x.UsageAndDosage
	}
	return ""
}

func (x *ExplainInfo) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *ExplainInfo) GetPackagingSpecification() string {
	if x != nil {
		return x.PackagingSpecification
	}
	return ""
}

func (x *ExplainInfo) GetBadnessReaction() string {
	if x != nil {
		return x.BadnessReaction
	}
	return ""
}

func (x *ExplainInfo) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ExplainInfo) GetValidTime() string {
	if x != nil {
		return x.ValidTime
	}
	return ""
}

func (x *ExplainInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *ExplainInfo) GetInteraction() string {
	if x != nil {
		return x.Interaction
	}
	return ""
}

func (x *ExplainInfo) GetRatifyNumber() string {
	if x != nil {
		return x.RatifyNumber
	}
	return ""
}

func (x *ExplainInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ExplainInfo) GetStandardNumber() string {
	if x != nil {
		return x.StandardNumber
	}
	return ""
}

func (x *ExplainInfo) GetPossessor() string {
	if x != nil {
		return x.Possessor
	}
	return ""
}

func (x *ExplainInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ExplainInfo) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *ExplainInfo) GetDosageForm() string {
	if x != nil {
		return x.DosageForm
	}
	return ""
}

type ListDrugRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FristCategoryId  int64                  `protobuf:"varint,1,opt,name=frist_category_id,json=fristCategoryId,proto3" json:"frist_category_id,omitempty"`
	SecondCategoryId int64                  `protobuf:"varint,2,opt,name=second_category_id,json=secondCategoryId,proto3" json:"second_category_id,omitempty"`
	Keyword          string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListDrugRequest) Reset() {
	*x = ListDrugRequest{}
	mi := &file_drug_v1_drug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrugRequest) ProtoMessage() {}

func (x *ListDrugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrugRequest.ProtoReflect.Descriptor instead.
func (*ListDrugRequest) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{7}
}

func (x *ListDrugRequest) GetFristCategoryId() int64 {
	if x != nil {
		return x.FristCategoryId
	}
	return 0
}

func (x *ListDrugRequest) GetSecondCategoryId() int64 {
	if x != nil {
		return x.SecondCategoryId
	}
	return 0
}

func (x *ListDrugRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListDrugReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Drug          []*InfoDrugs           `protobuf:"bytes,3,rep,name=drug,proto3" json:"drug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrugReply) Reset() {
	*x = ListDrugReply{}
	mi := &file_drug_v1_drug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrugReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrugReply) ProtoMessage() {}

func (x *ListDrugReply) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrugReply.ProtoReflect.Descriptor instead.
func (*ListDrugReply) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{8}
}

func (x *ListDrugReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListDrugReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListDrugReply) GetDrug() []*InfoDrugs {
	if x != nil {
		return x.Drug
	}
	return nil
}

type InfoDrugs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugName      string                 `protobuf:"bytes,1,opt,name=drug_name,json=drugName,proto3" json:"drug_name,omitempty"`
	Specification string                 `protobuf:"bytes,2,opt,name=specification,proto3" json:"specification,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	SalesVolume   float64                `protobuf:"fixed64,4,opt,name=sales_volume,json=salesVolume,proto3" json:"sales_volume,omitempty"`
	Inventory     int64                  `protobuf:"varint,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	ExhibitionUrl string                 `protobuf:"bytes,6,opt,name=exhibition_url,json=exhibitionUrl,proto3" json:"exhibition_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoDrugs) Reset() {
	*x = InfoDrugs{}
	mi := &file_drug_v1_drug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoDrugs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoDrugs) ProtoMessage() {}

func (x *InfoDrugs) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoDrugs.ProtoReflect.Descriptor instead.
func (*InfoDrugs) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{9}
}

func (x *InfoDrugs) GetDrugName() string {
	if x != nil {
		return x.DrugName
	}
	return ""
}

func (x *InfoDrugs) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *InfoDrugs) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InfoDrugs) GetSalesVolume() float64 {
	if x != nil {
		return x.SalesVolume
	}
	return 0
}

func (x *InfoDrugs) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *InfoDrugs) GetExhibitionUrl() string {
	if x != nil {
		return x.ExhibitionUrl
	}
	return ""
}

type GetGuideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuideRequest) Reset() {
	*x = GetGuideRequest{}
	mi := &file_drug_v1_drug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuideRequest) ProtoMessage() {}

func (x *GetGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuideRequest.ProtoReflect.Descriptor instead.
func (*GetGuideRequest) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{10}
}

func (x *GetGuideRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGuideReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Guide         *GuideInfo             `protobuf:"bytes,3,opt,name=guide,proto3" json:"guide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuideReply) Reset() {
	*x = GetGuideReply{}
	mi := &file_drug_v1_drug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuideReply) ProtoMessage() {}

func (x *GetGuideReply) ProtoReflect() protoreflect.Message {
	mi := &file_drug_v1_drug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuideReply.ProtoReflect.Descriptor instead.
func (*GetGuideReply) Descriptor() ([]byte, []int) {
	return file_drug_v1_drug_proto_rawDescGZIP(), []int{11}
}

func (x *GetGuideReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGuideReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGuideReply) GetGuide() *GuideInfo {
	if x != nil {
		return x.Guide
	}
	return nil
}

var File_drug_v1_drug_proto protoreflect.FileDescriptor

const file_drug_v1_drug_proto_rawDesc = "" +
	"\n" +
	"\x12drug/v1/drug.proto\x12\adrug.v1\x1a\x1cgoogle/api/annotations.proto\" \n" +
	"\x0eGetDrugRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"[\n" +
	"\fGetDrugReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x04drug\x18\x03 \x01(\v2\x11.drug.v1.InfoDrugR\x04drug\"\xf5\x01\n" +
	"\bInfoDrug\x12\x1b\n" +
	"\tdrug_name\x18\x01 \x01(\tR\bdrugName\x12$\n" +
	"\rspecification\x18\x02 \x01(\tR\rspecification\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\fsales_volume\x18\x04 \x01(\x01R\vsalesVolume\x12\x1c\n" +
	"\tinventory\x18\x05 \x01(\x03R\tinventory\x12%\n" +
	"\x0eexhibition_url\x18\x06 \x01(\tR\rexhibitionUrl\x12(\n" +
	"\x05guide\x18\a \x01(\v2\x12.drug.v1.GuideInfoR\x05guide\"\xb7\x01\n" +
	"\tGuideInfo\x12%\n" +
	"\x0emajor_function\x18\x01 \x01(\tR\rmajorFunction\x12(\n" +
	"\x10usage_and_dosage\x18\x02 \x01(\tR\x0eusageAndDosage\x12\x16\n" +
	"\x06taboos\x18\x03 \x01(\tR\x06taboos\x12#\n" +
	"\rspecial_crowd\x18\x04 \x01(\tR\fspecialCrowd\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\"#\n" +
	"\x11GetExplainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"g\n" +
	"\x0fGetExplainReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\aexplain\x18\x03 \x01(\v2\x14.drug.v1.ExplainInfoR\aexplain\"\xb3\x05\n" +
	"\vExplainInfo\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x02 \x01(\tR\tgoodsName\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06taboos\x18\x04 \x01(\tR\x06taboos\x12\x1a\n" +
	"\bfunction\x18\x05 \x01(\tR\bfunction\x12(\n" +
	"\x10usage_and_dosage\x18\a \x01(\tR\x0eusageAndDosage\x12\x1c\n" +
	"\tcharacter\x18\b \x01(\tR\tcharacter\x127\n" +
	"\x17packaging_specification\x18\t \x01(\tR\x16packagingSpecification\x12)\n" +
	"\x10badness_reaction\x18\n" +
	" \x01(\tR\x0fbadnessReaction\x12\x1c\n" +
	"\tcondition\x18\v \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"valid_time\x18\f \x01(\tR\tvalidTime\x12\x16\n" +
	"\x06notice\x18\r \x01(\tR\x06notice\x12 \n" +
	"\vinteraction\x18\x0e \x01(\tR\vinteraction\x12#\n" +
	"\rratify_number\x18\x0f \x01(\tR\fratifyNumber\x12\"\n" +
	"\fmanufacturer\x18\x10 \x01(\tR\fmanufacturer\x12'\n" +
	"\x0fstandard_number\x18\x11 \x01(\tR\x0estandardNumber\x12\x1c\n" +
	"\tpossessor\x18\x12 \x01(\tR\tpossessor\x12\x18\n" +
	"\aaddress\x18\x13 \x01(\tR\aaddress\x12$\n" +
	"\rspecification\x18\x14 \x01(\tR\rspecification\x12\x1f\n" +
	"\vdosage_form\x18\x15 \x01(\tR\n" +
	"dosageForm\"\x85\x01\n" +
	"\x0fListDrugRequest\x12*\n" +
	"\x11frist_category_id\x18\x01 \x01(\x03R\x0ffristCategoryId\x12,\n" +
	"\x12second_category_id\x18\x02 \x01(\x03R\x10secondCategoryId\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"]\n" +
	"\rListDrugReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04drug\x18\x03 \x03(\v2\x12.drug.v1.InfoDrugsR\x04drug\"\xcc\x01\n" +
	"\tInfoDrugs\x12\x1b\n" +
	"\tdrug_name\x18\x01 \x01(\tR\bdrugName\x12$\n" +
	"\rspecification\x18\x02 \x01(\tR\rspecification\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\fsales_volume\x18\x04 \x01(\x01R\vsalesVolume\x12\x1c\n" +
	"\tinventory\x18\x05 \x01(\x03R\tinventory\x12%\n" +
	"\x0eexhibition_url\x18\x06 \x01(\tR\rexhibitionUrl\"!\n" +
	"\x0fGetGuideRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\rGetGuideReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x05guide\x18\x03 \x01(\v2\x12.drug.v1.GuideInfoR\x05guide2\xe8\x02\n" +
	"\x04Drug\x12N\n" +
	"\aGetDrug\x12\x17.drug.v1.GetDrugRequest\x1a\x15.drug.v1.GetDrugReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/drug\x12V\n" +
	"\bListDrug\x12\x18.drug.v1.ListDrugRequest\x1a\x16.drug.v1.ListDrugReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/drug/list\x12_\n" +
	"\n" +
	"GetExplain\x12\x1a.drug.v1.GetExplainRequest\x1a\x18.drug.v1.GetExplainReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/drug/explain\x12W\n" +
	"\bGetGuide\x12\x18.drug.v1.GetGuideRequest\x1a\x16.drug.v1.GetGuideReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/drug/guideBE\n" +
	"\x16dev.kratos.api.drug.v1B\vdrugProtoV1P\x01Z\x1ckratos_client/api/drug/v1;v1b\x06proto3"

var (
	file_drug_v1_drug_proto_rawDescOnce sync.Once
	file_drug_v1_drug_proto_rawDescData []byte
)

func file_drug_v1_drug_proto_rawDescGZIP() []byte {
	file_drug_v1_drug_proto_rawDescOnce.Do(func() {
		file_drug_v1_drug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drug_v1_drug_proto_rawDesc), len(file_drug_v1_drug_proto_rawDesc)))
	})
	return file_drug_v1_drug_proto_rawDescData
}

var file_drug_v1_drug_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_drug_v1_drug_proto_goTypes = []any{
	(*GetDrugRequest)(nil),    // 0: drug.v1.GetDrugRequest
	(*GetDrugReply)(nil),      // 1: drug.v1.GetDrugReply
	(*InfoDrug)(nil),          // 2: drug.v1.InfoDrug
	(*GuideInfo)(nil),         // 3: drug.v1.GuideInfo
	(*GetExplainRequest)(nil), // 4: drug.v1.GetExplainRequest
	(*GetExplainReply)(nil),   // 5: drug.v1.GetExplainReply
	(*ExplainInfo)(nil),       // 6: drug.v1.ExplainInfo
	(*ListDrugRequest)(nil),   // 7: drug.v1.ListDrugRequest
	(*ListDrugReply)(nil),     // 8: drug.v1.ListDrugReply
	(*InfoDrugs)(nil),         // 9: drug.v1.InfoDrugs
	(*GetGuideRequest)(nil),   // 10: drug.v1.GetGuideRequest
	(*GetGuideReply)(nil),     // 11: drug.v1.GetGuideReply
}
var file_drug_v1_drug_proto_depIdxs = []int32{
	2,  // 0: drug.v1.GetDrugReply.drug:type_name -> drug.v1.InfoDrug
	3,  // 1: drug.v1.InfoDrug.guide:type_name -> drug.v1.GuideInfo
	6,  // 2: drug.v1.GetExplainReply.explain:type_name -> drug.v1.ExplainInfo
	9,  // 3: drug.v1.ListDrugReply.drug:type_name -> drug.v1.InfoDrugs
	3,  // 4: drug.v1.GetGuideReply.guide:type_name -> drug.v1.GuideInfo
	0,  // 5: drug.v1.Drug.GetDrug:input_type -> drug.v1.GetDrugRequest
	7,  // 6: drug.v1.Drug.ListDrug:input_type -> drug.v1.ListDrugRequest
	4,  // 7: drug.v1.Drug.GetExplain:input_type -> drug.v1.GetExplainRequest
	10, // 8: drug.v1.Drug.GetGuide:input_type -> drug.v1.GetGuideRequest
	1,  // 9: drug.v1.Drug.GetDrug:output_type -> drug.v1.GetDrugReply
	8,  // 10: drug.v1.Drug.ListDrug:output_type -> drug.v1.ListDrugReply
	5,  // 11: drug.v1.Drug.GetExplain:output_type -> drug.v1.GetExplainReply
	11, // 12: drug.v1.Drug.GetGuide:output_type -> drug.v1.GetGuideReply
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_drug_v1_drug_proto_init() }
func file_drug_v1_drug_proto_init() {
	if File_drug_v1_drug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drug_v1_drug_proto_rawDesc), len(file_drug_v1_drug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drug_v1_drug_proto_goTypes,
		DependencyIndexes: file_drug_v1_drug_proto_depIdxs,
		MessageInfos:      file_drug_v1_drug_proto_msgTypes,
	}.Build()
	File_drug_v1_drug_proto = out.File
	file_drug_v1_drug_proto_goTypes = nil
	file_drug_v1_drug_proto_depIdxs = nil
}
