// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: doctors/v1/doctors.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Doctors_DoctorsList_FullMethodName = "/doctors.v1.Doctors/DoctorsList"
)

// DoctorsClient is the client API for Doctors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type DoctorsClient interface {
	// Sends a greeting
	DoctorsList(ctx context.Context, in *DoctorsListRequest, opts ...grpc.CallOption) (*DoctorsListReply, error)
}

type doctorsClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorsClient(cc grpc.ClientConnInterface) DoctorsClient {
	return &doctorsClient{cc}
}

func (c *doctorsClient) DoctorsList(ctx context.Context, in *DoctorsListRequest, opts ...grpc.CallOption) (*DoctorsListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorsListReply)
	err := c.cc.Invoke(ctx, Doctors_DoctorsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorsServer is the server API for Doctors service.
// All implementations must embed UnimplementedDoctorsServer
// for forward compatibility.
//
// The greeting service definition.
type DoctorsServer interface {
	// Sends a greeting
	DoctorsList(context.Context, *DoctorsListRequest) (*DoctorsListReply, error)
	mustEmbedUnimplementedDoctorsServer()
}

// UnimplementedDoctorsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorsServer struct{}

func (UnimplementedDoctorsServer) DoctorsList(context.Context, *DoctorsListRequest) (*DoctorsListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorsList not implemented")
}
func (UnimplementedDoctorsServer) mustEmbedUnimplementedDoctorsServer() {}
func (UnimplementedDoctorsServer) testEmbeddedByValue()                 {}

// UnsafeDoctorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorsServer will
// result in compilation errors.
type UnsafeDoctorsServer interface {
	mustEmbedUnimplementedDoctorsServer()
}

func RegisterDoctorsServer(s grpc.ServiceRegistrar, srv DoctorsServer) {
	// If the following call pancis, it indicates UnimplementedDoctorsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Doctors_ServiceDesc, srv)
}

func _Doctors_DoctorsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorsServer).DoctorsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctors_DoctorsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorsServer).DoctorsList(ctx, req.(*DoctorsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Doctors_ServiceDesc is the grpc.ServiceDesc for Doctors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Doctors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doctors.v1.Doctors",
	HandlerType: (*DoctorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoctorsList",
			Handler:    _Doctors_DoctorsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doctors/v1/doctors.proto",
}
