// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: doctor/v1/doctor.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 短信发送
type SendSmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,2,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReq) Reset() {
	*x = SendSmsReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReq) ProtoMessage() {}

func (x *SendSmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReq.ProtoReflect.Descriptor instead.
func (*SendSmsReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmsReq) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type SendSmsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResp) Reset() {
	*x = SendSmsResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResp) ProtoMessage() {}

func (x *SendSmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResp.ProtoReflect.Descriptor instead.
func (*SendSmsResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSmsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 注册
type RegisterDoctorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,3,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDoctorReq) Reset() {
	*x = RegisterDoctorReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDoctorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDoctorReq) ProtoMessage() {}

func (x *RegisterDoctorReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDoctorReq.ProtoReflect.Descriptor instead.
func (*RegisterDoctorReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDoctorReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterDoctorReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterDoctorReq) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type RegisterDoctorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDoctorResp) Reset() {
	*x = RegisterDoctorResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDoctorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDoctorResp) ProtoMessage() {}

func (x *RegisterDoctorResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDoctorResp.ProtoReflect.Descriptor instead.
func (*RegisterDoctorResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDoctorResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterDoctorResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 登录
type LoginDoctorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,3,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginDoctorReq) Reset() {
	*x = LoginDoctorReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDoctorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDoctorReq) ProtoMessage() {}

func (x *LoginDoctorReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDoctorReq.ProtoReflect.Descriptor instead.
func (*LoginDoctorReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *LoginDoctorReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginDoctorReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginDoctorReq) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type LoginDoctorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	DId           int64                  `protobuf:"varint,3,opt,name=DId,proto3" json:"DId,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginDoctorResp) Reset() {
	*x = LoginDoctorResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDoctorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDoctorResp) ProtoMessage() {}

func (x *LoginDoctorResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDoctorResp.ProtoReflect.Descriptor instead.
func (*LoginDoctorResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{5}
}

func (x *LoginDoctorResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginDoctorResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginDoctorResp) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

func (x *LoginDoctorResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 个人资料认证
type AuthenticationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DId           int64                  `protobuf:"varint,1,opt,name=DId,proto3" json:"DId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                    //医生姓名
	Gender        string                 `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`                //性别
	BirthData     string                 `protobuf:"bytes,4,opt,name=BirthData,proto3" json:"BirthData,omitempty"`          //出生日期
	Email         string                 `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`                  //邮箱
	Avatar        string                 `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`                //头像
	LicenseNumber string                 `protobuf:"bytes,7,opt,name=LicenseNumber,proto3" json:"LicenseNumber,omitempty"`  //执业医师资格证号
	DepartmentId  int64                  `protobuf:"varint,8,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty"`   //科室ID
	HospitalId    int64                  `protobuf:"varint,9,opt,name=HospitalId,proto3" json:"HospitalId,omitempty"`       //医院ID
	Title         string                 `protobuf:"bytes,10,opt,name=Title,proto3" json:"Title,omitempty"`                 //职称
	Speciality    string                 `protobuf:"bytes,11,opt,name=Speciality,proto3" json:"Speciality,omitempty"`       //专业特长
	PracticeScope string                 `protobuf:"bytes,12,opt,name=PracticeScope,proto3" json:"PracticeScope,omitempty"` //执业范围
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationReq) Reset() {
	*x = AuthenticationReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationReq) ProtoMessage() {}

func (x *AuthenticationReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationReq.ProtoReflect.Descriptor instead.
func (*AuthenticationReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticationReq) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

func (x *AuthenticationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthenticationReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AuthenticationReq) GetBirthData() string {
	if x != nil {
		return x.BirthData
	}
	return ""
}

func (x *AuthenticationReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticationReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AuthenticationReq) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *AuthenticationReq) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *AuthenticationReq) GetHospitalId() int64 {
	if x != nil {
		return x.HospitalId
	}
	return 0
}

func (x *AuthenticationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AuthenticationReq) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *AuthenticationReq) GetPracticeScope() string {
	if x != nil {
		return x.PracticeScope
	}
	return ""
}

type AuthenticationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResp) Reset() {
	*x = AuthenticationResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResp) ProtoMessage() {}

func (x *AuthenticationResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResp.ProtoReflect.Descriptor instead.
func (*AuthenticationResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthenticationResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 获取医生个人信息
type GetDoctorProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int64                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorProfileReq) Reset() {
	*x = GetDoctorProfileReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorProfileReq) ProtoMessage() {}

func (x *GetDoctorProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorProfileReq.ProtoReflect.Descriptor instead.
func (*GetDoctorProfileReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{8}
}

func (x *GetDoctorProfileReq) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type GetDoctorProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Profile       *DoctorProfile         `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorProfileResp) Reset() {
	*x = GetDoctorProfileResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorProfileResp) ProtoMessage() {}

func (x *GetDoctorProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorProfileResp.ProtoReflect.Descriptor instead.
func (*GetDoctorProfileResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{9}
}

func (x *GetDoctorProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDoctorProfileResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDoctorProfileResp) GetProfile() *DoctorProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DoctorProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DId           int64                  `protobuf:"varint,1,opt,name=DId,proto3" json:"DId,omitempty"`
	DoctorCode    string                 `protobuf:"bytes,2,opt,name=DoctorCode,proto3" json:"DoctorCode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,9,opt,name=LicenseNumber,proto3" json:"LicenseNumber,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,10,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty"`
	HospitalId    int64                  `protobuf:"varint,11,opt,name=HospitalId,proto3" json:"HospitalId,omitempty"`
	Title         string                 `protobuf:"bytes,12,opt,name=Title,proto3" json:"Title,omitempty"`
	Speciality    string                 `protobuf:"bytes,13,opt,name=Speciality,proto3" json:"Speciality,omitempty"`
	PracticeScope string                 `protobuf:"bytes,14,opt,name=PracticeScope,proto3" json:"PracticeScope,omitempty"`
	Status        string                 `protobuf:"bytes,15,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,16,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,17,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorProfile) Reset() {
	*x = DoctorProfile{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorProfile) ProtoMessage() {}

func (x *DoctorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorProfile.ProtoReflect.Descriptor instead.
func (*DoctorProfile) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{10}
}

func (x *DoctorProfile) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

func (x *DoctorProfile) GetDoctorCode() string {
	if x != nil {
		return x.DoctorCode
	}
	return ""
}

func (x *DoctorProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *DoctorProfile) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *DoctorProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DoctorProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DoctorProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DoctorProfile) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DoctorProfile) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DoctorProfile) GetHospitalId() int64 {
	if x != nil {
		return x.HospitalId
	}
	return 0
}

func (x *DoctorProfile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DoctorProfile) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *DoctorProfile) GetPracticeScope() string {
	if x != nil {
		return x.PracticeScope
	}
	return ""
}

func (x *DoctorProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DoctorProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DoctorProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 更新医生个人信息
type UpdateDoctorProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DId           int64                  `protobuf:"varint,1,opt,name=DId,proto3" json:"DId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=Title,proto3" json:"Title,omitempty"`
	Speciality    string                 `protobuf:"bytes,8,opt,name=Speciality,proto3" json:"Speciality,omitempty"`
	PracticeScope string                 `protobuf:"bytes,9,opt,name=PracticeScope,proto3" json:"PracticeScope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoctorProfileReq) Reset() {
	*x = UpdateDoctorProfileReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoctorProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorProfileReq) ProtoMessage() {}

func (x *UpdateDoctorProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateDoctorProfileReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDoctorProfileReq) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

func (x *UpdateDoctorProfileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *UpdateDoctorProfileReq) GetPracticeScope() string {
	if x != nil {
		return x.PracticeScope
	}
	return ""
}

type UpdateDoctorProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoctorProfileResp) Reset() {
	*x = UpdateDoctorProfileResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoctorProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorProfileResp) ProtoMessage() {}

func (x *UpdateDoctorProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateDoctorProfileResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDoctorProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDoctorProfileResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 修改密码
type ChangePasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DId             int64                  `protobuf:"varint,1,opt,name=DId,proto3" json:"DId,omitempty"`
	OldPassword     string                 `protobuf:"bytes,2,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{13}
}

func (x *ChangePasswordReq) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ChangePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResp) Reset() {
	*x = ChangePasswordResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResp) ProtoMessage() {}

func (x *ChangePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResp.ProtoReflect.Descriptor instead.
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{14}
}

func (x *ChangePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChangePasswordResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 注销账号
type DeleteAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DId           int64                  `protobuf:"varint,1,opt,name=DId,proto3" json:"DId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountReq) Reset() {
	*x = DeleteAccountReq{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReq) ProtoMessage() {}

func (x *DeleteAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReq.ProtoReflect.Descriptor instead.
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteAccountReq) GetDId() int64 {
	if x != nil {
		return x.DId
	}
	return 0
}

type DeleteAccountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResp) Reset() {
	*x = DeleteAccountResp{}
	mi := &file_doctor_v1_doctor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResp) ProtoMessage() {}

func (x *DeleteAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_v1_doctor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResp.ProtoReflect.Descriptor instead.
func (*DeleteAccountResp) Descriptor() ([]byte, []int) {
	return file_doctor_v1_doctor_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAccountResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAccountResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_doctor_v1_doctor_proto protoreflect.FileDescriptor

const file_doctor_v1_doctor_proto_rawDesc = "" +
	"\n" +
	"\x16doctor/v1/doctor.proto\x12\rapi.doctor.v1\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\n" +
	"SendSmsReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12 \n" +
	"\vSendSmsCode\x18\x02 \x01(\tR\vSendSmsCode\";\n" +
	"\vSendSmsResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"g\n" +
	"\x11RegisterDoctorReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12 \n" +
	"\vSendSmsCode\x18\x03 \x01(\tR\vSendSmsCode\"B\n" +
	"\x12RegisterDoctorResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"d\n" +
	"\x0eLoginDoctorReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12 \n" +
	"\vSendSmsCode\x18\x03 \x01(\tR\vSendSmsCode\"g\n" +
	"\x0fLoginDoctorResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03DId\x18\x03 \x01(\x03R\x03DId\x12\x14\n" +
	"\x05Token\x18\x04 \x01(\tR\x05Token\"\xe3\x02\n" +
	"\x11AuthenticationReq\x12\x10\n" +
	"\x03DId\x18\x01 \x01(\x03R\x03DId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Gender\x18\x03 \x01(\tR\x06Gender\x12\x1c\n" +
	"\tBirthData\x18\x04 \x01(\tR\tBirthData\x12\x14\n" +
	"\x05Email\x18\x05 \x01(\tR\x05Email\x12\x16\n" +
	"\x06Avatar\x18\x06 \x01(\tR\x06Avatar\x12$\n" +
	"\rLicenseNumber\x18\a \x01(\tR\rLicenseNumber\x12\"\n" +
	"\fDepartmentId\x18\b \x01(\x03R\fDepartmentId\x12\x1e\n" +
	"\n" +
	"HospitalId\x18\t \x01(\x03R\n" +
	"HospitalId\x12\x14\n" +
	"\x05Title\x18\n" +
	" \x01(\tR\x05Title\x12\x1e\n" +
	"\n" +
	"Speciality\x18\v \x01(\tR\n" +
	"Speciality\x12$\n" +
	"\rPracticeScope\x18\f \x01(\tR\rPracticeScope\"B\n" +
	"\x12AuthenticationResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"2\n" +
	"\x13GetDoctorProfileReq\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x03R\bdoctorId\"|\n" +
	"\x14GetDoctorProfileResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x126\n" +
	"\aProfile\x18\x03 \x01(\v2\x1c.api.doctor.v1.DoctorProfileR\aProfile\"\xe9\x03\n" +
	"\rDoctorProfile\x12\x10\n" +
	"\x03DId\x18\x01 \x01(\x03R\x03DId\x12\x1e\n" +
	"\n" +
	"DoctorCode\x18\x02 \x01(\tR\n" +
	"DoctorCode\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Gender\x18\x04 \x01(\tR\x06Gender\x12\x1c\n" +
	"\tBirthDate\x18\x05 \x01(\tR\tBirthDate\x12\x14\n" +
	"\x05Phone\x18\x06 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\a \x01(\tR\x05Email\x12\x16\n" +
	"\x06Avatar\x18\b \x01(\tR\x06Avatar\x12$\n" +
	"\rLicenseNumber\x18\t \x01(\tR\rLicenseNumber\x12\"\n" +
	"\fDepartmentId\x18\n" +
	" \x01(\x03R\fDepartmentId\x12\x1e\n" +
	"\n" +
	"HospitalId\x18\v \x01(\x03R\n" +
	"HospitalId\x12\x14\n" +
	"\x05Title\x18\f \x01(\tR\x05Title\x12\x1e\n" +
	"\n" +
	"Speciality\x18\r \x01(\tR\n" +
	"Speciality\x12$\n" +
	"\rPracticeScope\x18\x0e \x01(\tR\rPracticeScope\x12\x16\n" +
	"\x06Status\x18\x0f \x01(\tR\x06Status\x12\x1c\n" +
	"\tCreatedAt\x18\x10 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x11 \x01(\tR\tUpdatedAt\"\xfe\x01\n" +
	"\x16UpdateDoctorProfileReq\x12\x10\n" +
	"\x03DId\x18\x01 \x01(\x03R\x03DId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Gender\x18\x03 \x01(\tR\x06Gender\x12\x1c\n" +
	"\tBirthDate\x18\x04 \x01(\tR\tBirthDate\x12\x14\n" +
	"\x05Email\x18\x05 \x01(\tR\x05Email\x12\x16\n" +
	"\x06Avatar\x18\x06 \x01(\tR\x06Avatar\x12\x14\n" +
	"\x05Title\x18\a \x01(\tR\x05Title\x12\x1e\n" +
	"\n" +
	"Speciality\x18\b \x01(\tR\n" +
	"Speciality\x12$\n" +
	"\rPracticeScope\x18\t \x01(\tR\rPracticeScope\"G\n" +
	"\x17UpdateDoctorProfileResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"\x93\x01\n" +
	"\x11ChangePasswordReq\x12\x10\n" +
	"\x03DId\x18\x01 \x01(\x03R\x03DId\x12 \n" +
	"\vOldPassword\x18\x02 \x01(\tR\vOldPassword\x12 \n" +
	"\vNewPassword\x18\x03 \x01(\tR\vNewPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x04 \x01(\tR\x0fConfirmPassword\"B\n" +
	"\x12ChangePasswordResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\"$\n" +
	"\x10DeleteAccountReq\x12\x10\n" +
	"\x03DId\x18\x01 \x01(\x03R\x03DId\"A\n" +
	"\x11DeleteAccountResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code2\x82\b\n" +
	"\x06Doctor\x12c\n" +
	"\aSendSms\x12\x19.api.doctor.v1.SendSmsReq\x1a\x1a.api.doctor.v1.SendSmsResp\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/doctor/SendSms\x12\x7f\n" +
	"\x0eRegisterDoctor\x12 .api.doctor.v1.RegisterDoctorReq\x1a!.api.doctor.v1.RegisterDoctorResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/doctor/RegisterDoctor\x12s\n" +
	"\vLoginDoctor\x12\x1d.api.doctor.v1.LoginDoctorReq\x1a\x1e.api.doctor.v1.LoginDoctorResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/doctor/LoginDoctor\x12\x7f\n" +
	"\x0eAuthentication\x12 .api.doctor.v1.AuthenticationReq\x1a!.api.doctor.v1.AuthenticationResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/doctor/Authentication\x12\x87\x01\n" +
	"\x10GetDoctorProfile\x12\".api.doctor.v1.GetDoctorProfileReq\x1a#.api.doctor.v1.GetDoctorProfileResp\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/doctor/GetDoctorProfile\x12\x93\x01\n" +
	"\x13UpdateDoctorProfile\x12%.api.doctor.v1.UpdateDoctorProfileReq\x1a&.api.doctor.v1.UpdateDoctorProfileResp\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/doctor/UpdateDoctorProfile\x12\x7f\n" +
	"\x0eChangePassword\x12 .api.doctor.v1.ChangePasswordReq\x1a!.api.doctor.v1.ChangePasswordResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/doctor/ChangePassword\x12{\n" +
	"\rDeleteAccount\x12\x1f.api.doctor.v1.DeleteAccountReq\x1a .api.doctor.v1.DeleteAccountResp\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/doctor/DeleteAccountB+\n" +
	"\rapi.doctor.v1P\x01Z\x18doctors/api/doctor/v1;v1b\x06proto3"

var (
	file_doctor_v1_doctor_proto_rawDescOnce sync.Once
	file_doctor_v1_doctor_proto_rawDescData []byte
)

func file_doctor_v1_doctor_proto_rawDescGZIP() []byte {
	file_doctor_v1_doctor_proto_rawDescOnce.Do(func() {
		file_doctor_v1_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doctor_v1_doctor_proto_rawDesc), len(file_doctor_v1_doctor_proto_rawDesc)))
	})
	return file_doctor_v1_doctor_proto_rawDescData
}

var file_doctor_v1_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_doctor_v1_doctor_proto_goTypes = []any{
	(*SendSmsReq)(nil),              // 0: api.doctor.v1.SendSmsReq
	(*SendSmsResp)(nil),             // 1: api.doctor.v1.SendSmsResp
	(*RegisterDoctorReq)(nil),       // 2: api.doctor.v1.RegisterDoctorReq
	(*RegisterDoctorResp)(nil),      // 3: api.doctor.v1.RegisterDoctorResp
	(*LoginDoctorReq)(nil),          // 4: api.doctor.v1.LoginDoctorReq
	(*LoginDoctorResp)(nil),         // 5: api.doctor.v1.LoginDoctorResp
	(*AuthenticationReq)(nil),       // 6: api.doctor.v1.AuthenticationReq
	(*AuthenticationResp)(nil),      // 7: api.doctor.v1.AuthenticationResp
	(*GetDoctorProfileReq)(nil),     // 8: api.doctor.v1.GetDoctorProfileReq
	(*GetDoctorProfileResp)(nil),    // 9: api.doctor.v1.GetDoctorProfileResp
	(*DoctorProfile)(nil),           // 10: api.doctor.v1.DoctorProfile
	(*UpdateDoctorProfileReq)(nil),  // 11: api.doctor.v1.UpdateDoctorProfileReq
	(*UpdateDoctorProfileResp)(nil), // 12: api.doctor.v1.UpdateDoctorProfileResp
	(*ChangePasswordReq)(nil),       // 13: api.doctor.v1.ChangePasswordReq
	(*ChangePasswordResp)(nil),      // 14: api.doctor.v1.ChangePasswordResp
	(*DeleteAccountReq)(nil),        // 15: api.doctor.v1.DeleteAccountReq
	(*DeleteAccountResp)(nil),       // 16: api.doctor.v1.DeleteAccountResp
}
var file_doctor_v1_doctor_proto_depIdxs = []int32{
	10, // 0: api.doctor.v1.GetDoctorProfileResp.Profile:type_name -> api.doctor.v1.DoctorProfile
	0,  // 1: api.doctor.v1.Doctor.SendSms:input_type -> api.doctor.v1.SendSmsReq
	2,  // 2: api.doctor.v1.Doctor.RegisterDoctor:input_type -> api.doctor.v1.RegisterDoctorReq
	4,  // 3: api.doctor.v1.Doctor.LoginDoctor:input_type -> api.doctor.v1.LoginDoctorReq
	6,  // 4: api.doctor.v1.Doctor.Authentication:input_type -> api.doctor.v1.AuthenticationReq
	8,  // 5: api.doctor.v1.Doctor.GetDoctorProfile:input_type -> api.doctor.v1.GetDoctorProfileReq
	11, // 6: api.doctor.v1.Doctor.UpdateDoctorProfile:input_type -> api.doctor.v1.UpdateDoctorProfileReq
	13, // 7: api.doctor.v1.Doctor.ChangePassword:input_type -> api.doctor.v1.ChangePasswordReq
	15, // 8: api.doctor.v1.Doctor.DeleteAccount:input_type -> api.doctor.v1.DeleteAccountReq
	1,  // 9: api.doctor.v1.Doctor.SendSms:output_type -> api.doctor.v1.SendSmsResp
	3,  // 10: api.doctor.v1.Doctor.RegisterDoctor:output_type -> api.doctor.v1.RegisterDoctorResp
	5,  // 11: api.doctor.v1.Doctor.LoginDoctor:output_type -> api.doctor.v1.LoginDoctorResp
	7,  // 12: api.doctor.v1.Doctor.Authentication:output_type -> api.doctor.v1.AuthenticationResp
	9,  // 13: api.doctor.v1.Doctor.GetDoctorProfile:output_type -> api.doctor.v1.GetDoctorProfileResp
	12, // 14: api.doctor.v1.Doctor.UpdateDoctorProfile:output_type -> api.doctor.v1.UpdateDoctorProfileResp
	14, // 15: api.doctor.v1.Doctor.ChangePassword:output_type -> api.doctor.v1.ChangePasswordResp
	16, // 16: api.doctor.v1.Doctor.DeleteAccount:output_type -> api.doctor.v1.DeleteAccountResp
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_doctor_v1_doctor_proto_init() }
func file_doctor_v1_doctor_proto_init() {
	if File_doctor_v1_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doctor_v1_doctor_proto_rawDesc), len(file_doctor_v1_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doctor_v1_doctor_proto_goTypes,
		DependencyIndexes: file_doctor_v1_doctor_proto_depIdxs,
		MessageInfos:      file_doctor_v1_doctor_proto_msgTypes,
	}.Build()
	File_doctor_v1_doctor_proto = out.File
	file_doctor_v1_doctor_proto_goTypes = nil
	file_doctor_v1_doctor_proto_depIdxs = nil
}
